//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWallet.Portal.CoreAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreAPI.IChannelAPI")]
    public interface IChannelAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelAPI/Process", ReplyAction="http://tempuri.org/IChannelAPI/ProcessResponse")]
        string Process(string Request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChannelAPI/Process", ReplyAction="http://tempuri.org/IChannelAPI/ProcessResponse")]
        System.IAsyncResult BeginProcess(string Request, System.AsyncCallback callback, object asyncState);
        
        string EndProcess(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChannelAPI/Echo", ReplyAction="http://tempuri.org/IChannelAPI/EchoResponse")]
        string Echo();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IChannelAPI/Echo", ReplyAction="http://tempuri.org/IChannelAPI/EchoResponse")]
        System.IAsyncResult BeginEcho(System.AsyncCallback callback, object asyncState);
        
        string EndEcho(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChannelAPIChannel : eWallet.Portal.CoreAPI.IChannelAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EchoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelAPIClient : System.ServiceModel.ClientBase<eWallet.Portal.CoreAPI.IChannelAPI>, eWallet.Portal.CoreAPI.IChannelAPI {
        
        private BeginOperationDelegate onBeginProcessDelegate;
        
        private EndOperationDelegate onEndProcessDelegate;
        
        private System.Threading.SendOrPostCallback onProcessCompletedDelegate;
        
        private BeginOperationDelegate onBeginEchoDelegate;
        
        private EndOperationDelegate onEndEchoDelegate;
        
        private System.Threading.SendOrPostCallback onEchoCompletedDelegate;
        
        public ChannelAPIClient() {
        }
        
        public ChannelAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ProcessCompletedEventArgs> ProcessCompleted;
        
        public event System.EventHandler<EchoCompletedEventArgs> EchoCompleted;
        
        public string Process(string Request) {
            return base.Channel.Process(Request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginProcess(string Request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginProcess(Request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndProcess(System.IAsyncResult result) {
            return base.Channel.EndProcess(result);
        }
        
        private System.IAsyncResult OnBeginProcess(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Request = ((string)(inValues[0]));
            return this.BeginProcess(Request, callback, asyncState);
        }
        
        private object[] OnEndProcess(System.IAsyncResult result) {
            string retVal = this.EndProcess(result);
            return new object[] {
                    retVal};
        }
        
        private void OnProcessCompleted(object state) {
            if ((this.ProcessCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ProcessCompleted(this, new ProcessCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ProcessAsync(string Request) {
            this.ProcessAsync(Request, null);
        }
        
        public void ProcessAsync(string Request, object userState) {
            if ((this.onBeginProcessDelegate == null)) {
                this.onBeginProcessDelegate = new BeginOperationDelegate(this.OnBeginProcess);
            }
            if ((this.onEndProcessDelegate == null)) {
                this.onEndProcessDelegate = new EndOperationDelegate(this.OnEndProcess);
            }
            if ((this.onProcessCompletedDelegate == null)) {
                this.onProcessCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProcessCompleted);
            }
            base.InvokeAsync(this.onBeginProcessDelegate, new object[] {
                        Request}, this.onEndProcessDelegate, this.onProcessCompletedDelegate, userState);
        }
        
        public string Echo() {
            return base.Channel.Echo();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginEcho(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEcho(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndEcho(System.IAsyncResult result) {
            return base.Channel.EndEcho(result);
        }
        
        private System.IAsyncResult OnBeginEcho(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginEcho(callback, asyncState);
        }
        
        private object[] OnEndEcho(System.IAsyncResult result) {
            string retVal = this.EndEcho(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEchoCompleted(object state) {
            if ((this.EchoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EchoCompleted(this, new EchoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EchoAsync() {
            this.EchoAsync(null);
        }
        
        public void EchoAsync(object userState) {
            if ((this.onBeginEchoDelegate == null)) {
                this.onBeginEchoDelegate = new BeginOperationDelegate(this.OnBeginEcho);
            }
            if ((this.onEndEchoDelegate == null)) {
                this.onEndEchoDelegate = new EndOperationDelegate(this.OnEndEcho);
            }
            if ((this.onEchoCompletedDelegate == null)) {
                this.onEchoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEchoCompleted);
            }
            base.InvokeAsync(this.onBeginEchoDelegate, null, this.onEndEchoDelegate, this.onEchoCompletedDelegate, userState);
        }
    }
}
